<?php $this->layout("app/template/base"); ?>

<?php $this->start("page-buttons") ?>
    <?php if ($permissao["inserir"]) : ?>
    <a class="btn btn-primary" href="<?=$router->route("admin.perfil.novo")?>"><i class="fa fa-plus fa-fw"></i> Novo Perfil</a>
    <?php endif ?>
<?php $this->end() ?>

<div class="card crud-table-card">
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-hover table-sm table-datatable table-datatable-alt crud-table">
                <thead>
                    <tr>
                        <th>Perfil</th>
                        <th>Descricao</th>
                        <th>Permissoes</th>
                        <th>Usuarios</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($dados as $d) : ?>
                        <tr>
                            <td><a class="edit" href="<?=$router->route("admin.perfil.editar", ["id" => $d->id])?>"><?=$d->nome?></a></td>
                            <td><?=$d->descricao ?: "-"?></td>
                            <td><?=$d->permissoes_total?></td>
                            <td><?=$d->usuarios?></td>
                            <td class="text-end">
                                <div class="table-actions">
                                    <a class="table-action-btn" data-tooltip="true" title="Editar" href="<?=$router->route("admin.perfil.editar", ["id" => $d->id])?>"><i class="uil-edit-alt"></i></a>
                                    <button type="button" class="table-action-btn table-action-danger" <?=$d->disabled?> <?php if (empty($d->disabled)) : ?>data-tooltip="true"<?php endif ?> title="<?=$d->title?>" <?=$d->action?>><i class="uil uil-trash"></i></button>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
