<form id="form-cliente-situacao" class="form-validate" action="<?=$url_action?>" method="POST">
    <input type="hidden" name="csrf" value="<?=$csrf?>">
    <?php if (!empty($situacao->id)) : ?>
        <input type="hidden" name="id" value="<?=$situacao->hash()?>">
    <?php endif ?>

    <div class="mb-3">
        <label for="descricao" class="form-label" title="Campo Obrigatório">Descrição <span class="text-danger">*</span></label>
        <input type="text" class="form-control" id="descricao" name="descricao" placeholder="Descrição" required value="<?=$situacao->descricao ?? ""?>">
    </div>

    <div class="row g-3">
        <div class="col-12 col-sm-6">
            <label for="cor" class="form-label">Cor</label>
            <input type="color" class="form-control form-control-color" id="cor" name="cor" value="<?=$situacao->cor ?? "#0d6efd"?>">
        </div>

        <div class="col-12 col-sm-6">
            <label for="ativo" class="form-label">Ativo</label>
            <select name="ativo" id="ativo" class="form-select" data-search="false">
                <option value="1" <?=(!isset($situacao->ativo) || (int) $situacao->ativo === 1) ? "selected" : ""?>>Sim</option>
                <option value="0" <?=isset($situacao->ativo) && (int) $situacao->ativo === 0 ? "selected" : ""?>>Não</option>
            </select>
            <small class="text-muted d-block mt-1">Marque como "não" para manter essa situação fora das movimentações do sistema.</small>
        </div>
    </div>
</form>
