<?= $this->insert("app/template/head"); ?>
<title><?=TITLE_SITE?> | Login</title>
<script src="https://kit.webawesome.com/d83c520fbd5f4726.js" crossorigin="anonymous"></script>
<script src="<?= asset("dist/notyf/notyf.min.js") ?>"></script>
<script src="<?= asset("app/js/login.min.js") ?>" defer></script>
<script>window.passwordMinLength = <?= (int)($password_min_length ?? 5) ?>;</script>
<?php if ($background) : ?>
<style type="text/css">
body {
    background: url("<?=$background?>") no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}
</style>
<?php endif ?>
<?php if ($recaptcha) : ?>
<script src="https://www.google.com/recaptcha/api.js?render=<?=$recaptcha?>" defer></script>
<script>rkey="<?=$recaptcha?>"</script>
<?php endif ?>
</head>

<body>
    <div class="authentication-page<?= ($template ?? "fluid") === "fluid" ? " fluid" : "" ?>">
        <?php if (($template ?? "fluid") === "fluid") : ?>
        <div class="wrapper">
        <?php endif ?>
            <div id="login-box" class="<?= ($template ?? "fluid") === "box" ? "bg-white rounded border-light" : "" ?> border-0 p-4 p-lg-5 m-auto">

                <?php if ($logo) : ?>
                    <div class="login-logo">
                        <img src="<?=$logo?>" alt="<?= app("name") ?>" height="<?= $logo_height ?? "100" ?>">
                    </div>
                <?php endif ?>

                <div class="text-center text-md-center mb-4 mt-md-0">
                    <h1 class="mb-0 h4"><?= $login_box_title ?></h1>
                    <?php if ($login_box_desc) : ?>
                        <p class="text-muted mt-2 mb-4"><?= $login_box_desc ?></p>
                    <?php endif ?>
                </div>

                <form id="form-login" action="<?=$action?>" method="POST" class="mt-4" validate>

                    <div class="form-group mb-4">
                        <label class="fw-medium mb-2" for="userLogin"><?=$input["user"]["label"]?></label>
                        <div class="input-group">
                            <span class="input-group-text bg-white" id="basic-addon1">
                                <i class="uil uil-user text-gray-600"></i>
                            </span>
                            <input type="<?= $input["user"]["type"] ?>" class="form-control form-control-lg border-start-0" name="login" id="userLogin" placeholder="<?= $input["user"]["placeholder"] ?>" autocomplete="username" autofocus>
                        </div>
                    </div>

                    <div class="form-group<?= ($template ?? "fluid") === "fluid" ? "" : " mb-4" ?>">
                        <?php if (($template ?? "fluid") === "fluid") : ?>
                        <div class="form-group mb-4">
                        <?php endif ?>
                            <label class="fw-medium mb-2" for="password"><?=$input["pass"]["label"]?></label>
                            <div class="input-group">
                                <span class="input-group-text bg-white" id="basic-addon2">
                                    <i class="uil uil-lock icon icon-xs text-gray-600"></i>
                                </span>
                                <input type="password" placeholder="<?= $input["pass"]["placeholder"] ?>" class="form-control form-control-lg border-start-0 border-end-0" id="password" name="senha" autocomplete="current-password">
                                <span class="input-group-text bg-white toggle-pass" id="basic-addon3">
                                    <i class="uil uil-eye icon icon-xs text-gray-600"></i>
                                </span>
                            </div>
                        <?php if (($template ?? "fluid") === "fluid") : ?>
                        </div>
                        <?php endif ?>

                        <div class="d-flex justify-content-between align-items-top mb-4 mt-4">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" value="1" name="remember" id="remember">
                                <label class="form-check-label mb-0" for="remember">
                                    Continuar conectado
                                </label>
                            </div>
                            <?php if ($recuperar_senha) : ?>
                            <div><a href="<?= $recuperar_senha ?>" class="small text-right">Esqueceu sua senha?</a></div>
                            <?php endif ?>
                        </div>
                    </div>

                    <input type="hidden" name="csrf" value="<?=$csrf?>">

                    <div class="d-grid">
                        <button type="submit" class="btn btn-primary btn-lg">Entrar</button>
                    </div>

                    <div id="login-message" class="mt-3"><?php flash() ?></div>

                </form>

            </div>
        <?php if (($template ?? "fluid") === "fluid") : ?>
        </div>
        <?php endif ?>
    </div>

</body>
</html>
